// Declares `*.png` as a static import. It has to sit in this file rather than
// in a `.d.ts` beside it: consuming apps compile this source directly, and
// their own tsconfigs only include their own `src`. They do carry the same
// reference in `next-env.d.ts` — but that file is generated by `next build`
// and gitignored, so a `typecheck` that runs before any build has no idea what
// a PNG is. CI does exactly that.
/// <reference types="next/image-types/global" />

import { cn, ORG } from "@byteveda/utils";
import Image from "next/image";
import Link from "next/link";

import mark from "./assets/byteveda-mark.png";

/** Rendered size. The artwork is taller than it is wide; height leads. */
const MARK_HEIGHT = 28;
const MARK_WIDTH = Math.round((mark.width / mark.height) * MARK_HEIGHT);

type WordmarkProps = {
  href?: string;
  /** Brand text; defaults to the org name, lowercased. */
  label?: string;
  className?: string;
};

/**
 * The ByteVeda brand lockup — leaf mark + wordmark.
 *
 * A bitmap rather than the inline SVG that used to live here: the mark is a
 * multi-tone gradient, so it cannot take `currentColor` and there is nothing
 * for a single path to carry. One source at three times the rendered size, so
 * a retina screen has pixels to use and `next/image` can size the rest down.
 *
 * No tile behind it. The old bracket was a white glyph that needed the accent
 * square to sit on; this one brings its own colour.
 */
export function Wordmark({ href = "/", label = ORG.toLowerCase(), className }: WordmarkProps) {
  return (
    <Link href={href} className={cn("brand", className)} aria-label={`${ORG} home`}>
      {/* Decorative: the lockup spells the name out, and the link is labelled. */}
      <Image
        className="mark"
        src={mark}
        width={MARK_WIDTH}
        height={MARK_HEIGHT}
        alt=""
        aria-hidden
        priority
      />
      <span>
        <b>{label}</b>
        <span className="dot">.</span>
      </span>
    </Link>
  );
}
