// Declares `*.png` as a static import. It has to sit in this file rather than
// in a `.d.ts` beside it: consuming apps compile this source directly, and
// their own tsconfigs only include their own `src`. They do carry the same
// reference in `next-env.d.ts` — but that file is generated by `next build`
// and gitignored, so a `typecheck` that runs before any build has no idea what
// a PNG is. CI does exactly that.
/// <reference types="next/image-types/global" />

import Image from "next/image";
import Link from "next/link";
import mark from "./assets/byteveda-mark.png";
import { cn } from "./internal";

/** Rendered size. The artwork is taller than it is wide; height leads. */
const MARK_HEIGHT = 28;

/**
 * Width over height of `assets/byteveda-mark.png`, 63×84. Written down rather
 * than read off the import: Turbopack hands a PNG that lives in `node_modules`
 * to its importer as a bare URL string, not the `{ src, width, height }` it
 * gives an app's own images, so `mark.width` is `undefined` once this package
 * is installed from npm. `next/image` takes either shape for `src`.
 */
const MARK_RATIO = 63 / 84;

/** The artwork is ByteVeda's, so the name travels with it. */
const ORG = "ByteVeda";

/**
 * The leaf on its own, for a lockup that sets its own wording.
 *
 * A bitmap rather than the inline SVG that used to live here: the mark is a
 * multi-tone gradient, so it cannot take `currentColor` and there is nothing
 * for a single path to carry. One source at three times the rendered size, so
 * a retina screen has pixels to use and `next/image` can size the rest down.
 */
export function BrandMark({ height = MARK_HEIGHT, className }: BrandMarkProps) {
  return (
    // Decorative: every lockup that uses it spells the name out beside it.
    <Image
      className={cn("mark", className)}
      src={mark}
      width={Math.round(MARK_RATIO * height)}
      height={height}
      alt=""
      aria-hidden
      priority
    />
  );
}

type BrandMarkProps = {
  /** Rendered height in px; the width follows the artwork's ratio. */
  height?: number;
  className?: string;
};

type WordmarkProps = {
  href?: string;
  /** Brand text; defaults to the org name, lowercased. */
  label?: string;
  className?: string;
};

/**
 * The ByteVeda brand lockup — leaf mark + wordmark.
 *
 * No tile behind it. The old bracket was a white glyph that needed the accent
 * square to sit on; this one brings its own colour.
 */
export function Wordmark({ href = "/", label = ORG.toLowerCase(), className }: WordmarkProps) {
  return (
    <Link href={href} className={cn("brand", className)} aria-label={`${ORG} home`}>
      <BrandMark />
      <span>
        <b>{label}</b>
        <span className="dot">.</span>
      </span>
    </Link>
  );
}
